GET http://localhost:8080/events

###

GET http://localhost:8080/events/63fda965141dacf3c2635d3d

###

POST http://localhost:8080/events
Content-Type: application/json

{
    "date": "02/15/2023",
    "title": "Meeting",
    "startTime":"1:15PM" ,
    "endTime":"5:00PM"
}

###

DELETE http://localhost:8080/events/63fe4a51446f89334207c737

###

PATCH http://localhost:8080/events/63fdbc950559b6749116a420
Content-Type: application/json

{
    "date": "02/15/2023",
    "title": "Birthday"
}
