name: Deploy to EC2

on:
  push:
    branches:
      - aws
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: Delete old files in target directory
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-178-36-70.ap-northeast-1.compute.amazonaws.com
          username: ec2-user
          port: 22
          key: ${{ secrets.KEY }}
          script: |
            cd ~/CalendarApp
            rm -rf *
            
      - name: Copy server files to EC2 instances
        uses: appleboy/scp-action@master
        with:
          host: ec2-54-178-36-70.ap-northeast-1.compute.amazonaws.com
          username: ec2-user
          port: 22
          key: ${{ secrets.KEY }}
          source: "."
          target: "~/CalendarApp"
      

      - name: Connect to EC2 instance via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-178-36-70.ap-northeast-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ec2-user/CalendarApp/server
            npm install
            npm install mongodb mongoose
            npm install bcrypt crypto dotenv express getstream stream-chat@4.1.0 nodemon twilio --force
            npm install cors
            pm2 stop all
            pm2 delete all
            pm2 start index.js
            cd /home/ec2-user/CalendarApp/client
            npm install
            npm install react@17.0.2 react-dom@17.0.2 --force
            npm install stream-chat stream-chat-react universal-cookie --force
            npm install axios --force
            npm install uuid --force
            pm2 start npm --name "my-app" -- start


    

